import { createMcpCommand, optionalBoolean, optionalJson, optionalJsonString, optionalNumber, optionalString, requiredJsonString } from '../shared.js';

export const drilldownUsers = createMcpCommand({
  command: '+drilldown_users',
  description: 'Drill down to the user list for a specific data point in an existing analysis result. Use only after query_adhoc, query_report_data, or query_dashboard_report_data, and keep qp consistent with the source analysis.',
  flags: [
    { name: 'project_id', type: 'number', required: true, desc: 'Project ID', alias: 'p' },
    { name: 'model_type', type: 'string', required: true, desc: 'Model type used in the source analysis. Supported values: event, retention, funnel, distribution, attribution, heat_map, interval, path, rank_list, prop_analysis, sql.' },
    { name: 'qp', type: 'json', required: true, desc: 'Query parameter JSON from the source analysis. Keep it consistent with the original analysis.' },
    { name: 'properties', type: 'json', required: false, desc: 'Optional user properties JSON array. If omitted, default properties are returned.' },
    { name: 'zone_offset', type: 'number', required: false, desc: 'Time zone offset in hours. For example, UTC+8 is 8' },
    { name: 'drilldown_date', type: 'string', required: false, desc: 'Target drilldown date from the analysis result. Format: yyyy-MM-dd' },
    { name: 'drilldown_groups', type: 'json', required: false, desc: 'Drilldown group values from the analysis result as a JSON array, for example ["ios"]' },
    { name: 'event_index', type: 'number', required: false, desc: 'Event index for event-model drilldown. Use the event position from the analysis result starting from 0.' },
    { name: 'is_lost', type: 'boolean', required: false, desc: 'For retention analysis, true queries lost users and false queries retained users. Default: false' },
    { name: 'retention_days', type: 'number', required: false, desc: 'Retention interval in days from the analysis result, for example 7 for day-7 retention' },
    { name: 'is_churned_user', type: 'boolean', required: false, desc: 'For funnel analysis, true queries churned users and false queries converted users. Default: false' },
    { name: 'funnel_step', type: 'number', required: false, desc: 'Funnel step number from the analysis result starting from 1' },
    { name: 'interval', type: 'string', required: false, desc: 'Interval used for interval analysis' },
    { name: 'distribution_bucket', type: 'number', required: false, desc: 'Distribution bucket index from the analysis result' },
    { name: 'compare_index', type: 'number', required: false, desc: 'Comparison index used in comparison analysis scenarios' },
    { name: 'include_total', type: 'boolean', required: false, desc: 'Whether to query users from the total row. Default: false' },
    { name: 'relation_val', type: 'string', required: false, desc: 'Relation value used in relation analysis scenarios' },
    { name: 'use_cache', type: 'boolean', required: false, desc: 'Whether to use cache. Default: true' },
    { name: 'timeout_minutes', type: 'number', required: false, desc: 'Query timeout in minutes. If omitted, 30 minutes is used.' },
  ],
  risk: 'read',
  buildArgs: (ctx) => ({
      projectId: ctx.num('project_id'),
      modelType: ctx.str('model_type'),
      qp: requiredJsonString(ctx, 'qp'),
      properties: optionalJsonString(ctx, 'properties'),
      zoneOffset: optionalNumber(ctx, 'zone_offset'),
      drilldownDate: optionalString(ctx, 'drilldown_date'),
      drilldownGroups: optionalJsonString(ctx, 'drilldown_groups'),
      eventIndex: optionalNumber(ctx, 'event_index'),
      isLost: optionalBoolean(ctx, 'is_lost'),
      retentionDays: optionalNumber(ctx, 'retention_days'),
      isChurnedUser: optionalBoolean(ctx, 'is_churned_user'),
      funnelStep: optionalNumber(ctx, 'funnel_step'),
      interval: optionalString(ctx, 'interval'),
      distributionBucket: optionalNumber(ctx, 'distribution_bucket'),
      compareIndex: optionalNumber(ctx, 'compare_index'),
      includeTotal: optionalBoolean(ctx, 'include_total'),
      relationVal: optionalString(ctx, 'relation_val'),
      useCache: optionalBoolean(ctx, 'use_cache'),
      timeoutMinutes: optionalNumber(ctx, 'timeout_minutes'),
    }),
});
