import { assertLimitWithinCap, createMcpCommand, DEFAULT_QUERY_LIMIT, optionalBoolean, optionalJson, optionalJsonString, optionalNumber, optionalString, requiredJsonString } from '../shared.js';

export const drilldownUserEvents = createMcpCommand({
  command: '+drilldown_user_events',
  description: 'Drill down to detailed event sequences for a specific user on specific dates. Use the result of drilldown_users and keep event names and dates consistent with the source analysis. For long-running or cancelable queries, requestId is required and must be provided before starting. For any query that may exceed the CLI or MCP HTTP timeout, generate requestId first so you can call +cancel_query --request_id <same value> if you stop waiting or the request returns fetch failed. If fetch failed, HTTP timeout, or caller timeout happens, the backend query may still be running. requestId must use mcp_<32 lowercase hex UUID>, for example mcp_0123456789abcdef0123456789abcdef. Submitted queries return metadata.requestId; pass that value to cancel_query(requestId) when the query is no longer needed. requestId is not auto-generated for MCP query tools because the caller must know it before the response for proactive cleanup. If requestId is omitted or blank, the backend returns REQUEST_ID_REQUIRED; invalid format returns INVALID_REQUEST_ID.',
  flags: [
    { name: 'project_id', type: 'number', required: true, desc: 'Project ID', alias: 'p' },
    { name: 'user_id', type: 'string', required: true, desc: 'User ID from drilldown_users' },
    { name: 'event_names', type: 'json', required: true, desc: 'JSON array of event names' },
    { name: 'target_dates', type: 'json', required: true, desc: 'JSON array of discrete target dates' },
    { name: 'zone_offset', type: 'number', required: false, desc: 'Time zone offset in hours. For example, UTC+8 is 8' },
    { name: 'properties', type: 'json', required: false, desc: 'Optional event properties JSON array' },
    { name: 'time_granularity', type: 'string', required: false, desc: 'Time granularity. Supported values: T0, T1, T2, T3, T4, T5, T6, T7' },
    { name: 'first_day_of_week', type: 'number', required: false, desc: 'First day of week. Supported values: 1-7' },
    { name: 'sort_order', type: 'string', required: false, desc: 'Sort order. Supported values: asc and desc' },
    { name: 'event_name_filter', type: 'string', required: false, desc: 'Optional event name filter' },
    { name: 'time_filter', type: 'string', required: false, desc: 'Optional time filter condition' },
    { name: 'time_filter_before_nums', type: 'number', required: false, desc: 'Number of records before the time filter point' },
    { name: 'time_filter_after_nums', type: 'number', required: false, desc: 'Number of records after the time filter point' },
    { name: 'entity_id', type: 'number', required: false, desc: 'Optional entity ID for multi-entity scenarios' },
    { name: 'entity_value', type: 'string', required: false, desc: 'Optional entity value for multi-entity scenarios' },
    { name: 'use_cache', type: 'boolean', required: false, desc: 'Whether to use cache. Default: true' },
    { name: 'page_num', type: 'number', required: false, desc: 'Start page number. Default: 1' },
    { name: 'page_size', type: 'number', required: false, desc: 'Page size. Default: 1000, maximum: 10000.' },
    { name: 'request_id', type: 'string', required: true, desc: 'Required unique request ID used for tracking and cancellation. Generate it before starting the query. It must use mcp_<32 lowercase hex UUID>, for example mcp_0123456789abcdef0123456789abcdef. Provide this before starting the query so it can be cancelled later with +cancel_query --request_id <same value>, even if the caller stops waiting before the tool returns. If fetch failed, HTTP timeout, or caller timeout happens, the backend query may still be running. requestId is not auto-generated for MCP query tools because the caller must know it before the response for proactive cleanup. If omitted or blank, the backend returns REQUEST_ID_REQUIRED; invalid format returns INVALID_REQUEST_ID. The response metadata.requestId echoes the supplied requestId and can also be passed to cancel_query(requestId) when the query is no longer needed.' },
    { name: 'timeout_minutes', type: 'number', required: false, desc: 'Query timeout in minutes. If omitted, 30 minutes is used.' },
  ],
  risk: 'read',
  validate: (ctx) => {
    assertLimitWithinCap(optionalNumber(ctx, 'page_size'), 'page_size');
  },
  buildArgs: (ctx) => ({
      projectId: ctx.num('project_id'),
      userId: ctx.str('user_id'),
      eventNames: requiredJsonString(ctx, 'event_names'),
      targetDates: requiredJsonString(ctx, 'target_dates'),
      zoneOffset: optionalNumber(ctx, 'zone_offset'),
      properties: optionalJsonString(ctx, 'properties'),
      timeGranularity: optionalString(ctx, 'time_granularity'),
      firstDayOfWeek: optionalNumber(ctx, 'first_day_of_week'),
      sortOrder: optionalString(ctx, 'sort_order'),
      eventNameFilter: optionalString(ctx, 'event_name_filter'),
      timeFilter: optionalString(ctx, 'time_filter'),
      timeFilterBeforeNums: optionalNumber(ctx, 'time_filter_before_nums'),
      timeFilterAfterNums: optionalNumber(ctx, 'time_filter_after_nums'),
      entityId: optionalNumber(ctx, 'entity_id'),
      entityValue: optionalString(ctx, 'entity_value'),
      useCache: optionalBoolean(ctx, 'use_cache'),
      pageNum: optionalNumber(ctx, 'page_num'),
      pageSize: optionalNumber(ctx, 'page_size') ?? DEFAULT_QUERY_LIMIT,
      requestId: ctx.str('request_id'),
      timeoutMinutes: optionalNumber(ctx, 'timeout_minutes'),
    }),
});
