import { createMcpCommand, optionalBoolean, optionalJson, optionalJsonString, optionalNumber, optionalString, requiredJsonString } from '../shared.js';

export const drilldownUserEvents = createMcpCommand({
  command: '+drilldown_user_events',
  description: 'Drill down to detailed event sequences for a specific user on specific dates. Use the result of drilldown_users and keep event names and dates consistent with the source analysis.',
  flags: [
    { name: 'project_id', type: 'number', required: true, desc: 'Project ID', alias: 'p' },
    { name: 'user_id', type: 'string', required: true, desc: 'User ID from drilldown_users' },
    { name: 'event_names', type: 'json', required: true, desc: 'JSON array of event names' },
    { name: 'target_dates', type: 'json', required: true, desc: 'JSON array of discrete target dates' },
    { name: 'zone_offset', type: 'number', required: false, desc: 'Time zone offset in hours. For example, UTC+8 is 8' },
    { name: 'properties', type: 'json', required: false, desc: 'Optional event properties JSON array' },
    { name: 'time_granularity', type: 'string', required: false, desc: 'Time granularity. Supported values: T0, T1, T2, T3, T4, T5, T6, T7' },
    { name: 'first_day_of_week', type: 'number', required: false, desc: 'First day of week. Supported values: 1-7' },
    { name: 'sort_order', type: 'string', required: false, desc: 'Sort order. Supported values: asc and desc' },
    { name: 'event_name_filter', type: 'string', required: false, desc: 'Optional event name filter' },
    { name: 'time_filter', type: 'string', required: false, desc: 'Optional time filter condition' },
    { name: 'time_filter_before_nums', type: 'number', required: false, desc: 'Number of records before the time filter point' },
    { name: 'time_filter_after_nums', type: 'number', required: false, desc: 'Number of records after the time filter point' },
    { name: 'entity_id', type: 'number', required: false, desc: 'Optional entity ID for multi-entity scenarios' },
    { name: 'entity_value', type: 'string', required: false, desc: 'Optional entity value for multi-entity scenarios' },
    { name: 'use_cache', type: 'boolean', required: false, desc: 'Whether to use cache. Default: true' },
    { name: 'page_num', type: 'number', required: false, desc: 'Start page number. Default: 1' },
    { name: 'page_size', type: 'number', required: false, desc: 'Page size. Default: 100' },
    { name: 'timeout_minutes', type: 'number', required: false, desc: 'Query timeout in minutes. If omitted, 30 minutes is used.' },
  ],
  risk: 'read',
  buildArgs: (ctx) => ({
      projectId: ctx.num('project_id'),
      userId: ctx.str('user_id'),
      eventNames: requiredJsonString(ctx, 'event_names'),
      targetDates: requiredJsonString(ctx, 'target_dates'),
      zoneOffset: optionalNumber(ctx, 'zone_offset'),
      properties: optionalJsonString(ctx, 'properties'),
      timeGranularity: optionalString(ctx, 'time_granularity'),
      firstDayOfWeek: optionalNumber(ctx, 'first_day_of_week'),
      sortOrder: optionalString(ctx, 'sort_order'),
      eventNameFilter: optionalString(ctx, 'event_name_filter'),
      timeFilter: optionalString(ctx, 'time_filter'),
      timeFilterBeforeNums: optionalNumber(ctx, 'time_filter_before_nums'),
      timeFilterAfterNums: optionalNumber(ctx, 'time_filter_after_nums'),
      entityId: optionalNumber(ctx, 'entity_id'),
      entityValue: optionalString(ctx, 'entity_value'),
      useCache: optionalBoolean(ctx, 'use_cache'),
      pageNum: optionalNumber(ctx, 'page_num'),
      pageSize: optionalNumber(ctx, 'page_size'),
      timeoutMinutes: optionalNumber(ctx, 'timeout_minutes'),
    }),
});
