import { createReadStream, readFileSync, statSync } from 'node:fs';
import { basename, dirname, resolve } from 'node:path';
import { createInterface } from 'node:readline';
import type { Command, RuntimeContext } from '../../framework/types.js';
import { CliValidationError, LocalDataUploadError } from '../../core/errors.js';
import { sha256File } from './input.js';
import type { LocalDataManifest } from './types.js';

const DEFAULT_BATCH_SIZE = 500;
const MAX_BATCH_SIZE = 1000;

interface PreparedUpload {
  endpoint: string;
  appid: string;
  ueFile: string;
  manifest: LocalDataManifest;
  batchSize: number;
  resumeFrom: number;
  recordCount: number;
  fileBytes: number;
  batchCount: number;
}

interface TransportResult {
  code: 0;
  http_status: number;
  request_bytes: number;
  response_bytes: number;
}

export const dataIntegrationUpload: Command = {
  service: 'data-integration',
  command: 'upload',
  usesAeHost: false,
  description: 'Sequentially submit validated UE JSONL to an explicit receiver /sync_json endpoint.',
  flags: [
    { name: 'ue-file', type: 'string', required: true, sensitive: true, desc: 'Validated valid.ue.jsonl generated by ae-cli data-integration convert.' },
    { name: 'manifest', type: 'string', required: true, sensitive: true, desc: 'Matching ae-local-data-manifest/v1 file.' },
    { name: 'endpoint', type: 'string', required: true, sensitive: true, desc: 'Complete receiver URL ending in /sync_json. Unrelated to --host.' },
    { name: 'appid', type: 'string', required: true, sensitive: true, desc: 'Destination project APPID. Never stored in generated artifacts or logs.' },
    { name: 'batch-size', type: 'number', default: DEFAULT_BATCH_SIZE, min: 1, max: MAX_BATCH_SIZE, desc: `Sequential records per request. Maximum: ${MAX_BATCH_SIZE}.` },
    { name: 'resume-from', type: 'number', default: 0, min: 0, desc: 'Zero-based record offset selected by the user after verifying an interrupted upload.' },
    { name: 'allow-clean-subset', type: 'boolean', default: false, desc: 'Explicitly allow valid rows from a blocked manifest after reviewing quarantine statistics.' },
    { name: 'retry', type: 'boolean', default: false, desc: 'After the default 3 transport retries, split a still-uncertain batch into single-record retries and report per-record failures.' },
    { name: 'compress', type: 'string', default: 'none', desc: 'Request body compression: gzip or none.' },
    { name: 'debug', type: 'boolean', default: false, desc: 'Mark every sync_json record debug=1 so AE returns per-record validation details. Testing only; not for production.' },
  ],
  risk: 'write',
  validate: (ctx) => {
    resolveSyncJsonEndpoint(ctx.str('endpoint'));
    const batchSize = ctx.num('batch-size');
    const resumeFrom = ctx.num('resume-from');
    const compress = ctx.str('compress').trim().toLowerCase();
    if (compress !== 'gzip' && compress !== 'none') {
      throw new CliValidationError('Compression must be gzip or none.', {
        code: 'LOCAL_DATA_COMPRESS_INVALID',
        location: { field: 'compress' },
      });
    }
    if (!Number.isInteger(batchSize) || batchSize < 1 || batchSize > MAX_BATCH_SIZE) {
      throw new CliValidationError(`Batch size must be an integer between 1 and ${MAX_BATCH_SIZE}.`, {
        code: 'LOCAL_DATA_BATCH_SIZE_INVALID',
        location: { field: 'batch-size' },
      });
    }
    if (!Number.isInteger(resumeFrom) || resumeFrom < 0) {
      throw new CliValidationError('Resume position must be a non-negative integer.', {
        code: 'LOCAL_DATA_RESUME_INVALID',
        location: { field: 'resume-from' },
      });
    }
  },
  dryRun: async (ctx) => {
    const prepared = await prepareUpload(ctx, false);
    return {
      action: 'upload_local_ue_data',
      target: maskEndpoint(prepared.endpoint),
      appid: maskAppid(prepared.appid),
      file_sha256: prepared.manifest.output.valid_sha256,
      record_count: prepared.recordCount,
      resume_from: prepared.resumeFrom,
      remaining_records: Math.max(0, prepared.recordCount - prepared.resumeFrom),
      batch_size: prepared.batchSize,
      batch_count: prepared.batchCount,
      bytes: prepared.fileBytes,
      manifest_status: prepared.manifest.status,
      upload_allowed: prepared.manifest.status === 'ready' || ctx.bool('allow-clean-subset'),
      authentication_headers: false,
      transport_retries: 3,
      split_uncertain_batches: ctx.bool('retry'),
      compression: ctx.str('compress').trim().toLowerCase() === 'gzip' ? 'gzip' : 'none',
      debug: ctx.bool('debug'),
      persistence_verified: false,
    };
  },
  execute: async (ctx) => {
    const prepared = await prepareUpload(ctx, true);
    const salvageUncertain = ctx.bool('retry');
    const compress = ctx.str('compress').trim().toLowerCase() === 'gzip' ? 'gzip' : undefined;
    const debug = ctx.bool('debug');
    const transportOptions = { retries: 3, retryDelayMs: 2000, compress };
    let submittedRecords = 0;
    let submittedBatches = 0;
    let processedRecords = 0;
    let requestBytes = 0;
    let responseBytes = 0;
    const failedRecords: number[] = [];
    for await (const batch of readUeBatches(prepared.ueFile, prepared.resumeFrom, prepared.batchSize)) {
      const batchStart = prepared.resumeFrom + processedRecords;
      const body = assembleSyncJsonBody(batch, prepared.appid, debug);
      try {
        const transport = await ctx.localDataUpload(prepared.endpoint, body, transportOptions) as TransportResult;
        submittedRecords += batch.length;
        submittedBatches += 1;
        requestBytes += transport.request_bytes;
        responseBytes += transport.response_bytes;
      } catch (error) {
        if (!salvageUncertain || !(error instanceof LocalDataUploadError) || error.meta?.delivery_state !== 'unknown') {
          throw decorateBatchError(error, submittedRecords, submittedBatches, batchStart, batch.length);
        }
        // Uncertain batch delivery: salvage by splitting into single-record requests and
        // collecting the offsets that still fail instead of stopping the whole upload.
        for (let index = 0; index < batch.length; index += 1) {
          const offset = batchStart + index;
          try {
            const single = await ctx.localDataUpload(
              prepared.endpoint,
              assembleSyncJsonBody([batch[index]], prepared.appid, debug),
              transportOptions,
            ) as TransportResult;
            submittedRecords += 1;
            submittedBatches += 1;
            requestBytes += single.request_bytes;
            responseBytes += single.response_bytes;
          } catch {
            failedRecords.push(offset);
          }
        }
      }
      processedRecords += batch.length;
    }
    if (failedRecords.length > 0) {
      return {
        status: 'partially_delivered',
        code: 0,
        delivery_state: 'partially_delivered',
        submitted_records: submittedRecords,
        submitted_batches: submittedBatches,
        resume_from: prepared.resumeFrom,
        failed_records: failedRecords,
        failed_count: failedRecords.length,
        request_bytes: requestBytes,
        response_bytes: responseBytes,
        persistence_verified: false,
        retry_attempted: true,
        next_step: 'Verify received data in AE before treating the upload as persisted.',
      };
    }
    return {
      status: 'receiver_accepted',
      code: 0,
      delivery_state: 'receiver_accepted',
      submitted_records: submittedRecords,
      submitted_batches: submittedBatches,
      resume_from: prepared.resumeFrom,
      request_bytes: requestBytes,
      response_bytes: responseBytes,
      persistence_verified: false,
      retry_attempted: false,
      next_step: 'Verify received data in AE before treating the upload as persisted.',
    };
  },
};

export function resolveSyncJsonEndpoint(raw: string): string {
  let url: URL;
  try {
    url = new URL(raw.trim());
  } catch {
    throw endpointError();
  }
  const validProtocol = url.protocol === 'http:' || url.protocol === 'https:';
  const forbidden = Boolean(url.username || url.password || url.search || url.hash);
  if (!validProtocol || forbidden || !url.pathname.endsWith('/sync_json')) throw endpointError();
  return url.toString();
}

export function assembleSyncJsonBody(lines: string[], appid: string, debug = false): string {
  const appidJson = JSON.stringify(appid);
  const debugValue = debug ? 1 : 0;
  return `[${lines.map((line) => `{"appid":${appidJson},"debug":${debugValue},"data":${line}}`).join(',')}]`;
}

async function prepareUpload(ctx: RuntimeContext, enforceReady: boolean): Promise<PreparedUpload> {
  const endpoint = resolveSyncJsonEndpoint(ctx.str('endpoint'));
  const appid = ctx.str('appid').trim();
  if (!appid || appid.length > 256) {
    throw new CliValidationError('APPID must be a non-empty value of at most 256 characters.', {
      code: 'LOCAL_DATA_APPID_INVALID',
      location: { field: 'appid' },
    });
  }
  const manifestPath = resolve(ctx.str('manifest'));
  const manifest = readManifest(manifestPath);
  const ueFile = resolve(ctx.str('ue-file'));
  const expectedFile = resolve(dirname(manifestPath), manifest.output.valid_file);
  if (ueFile !== expectedFile) {
    throw new CliValidationError('The UE file does not match the manifest output path.', {
      code: 'LOCAL_DATA_MANIFEST_FILE_MISMATCH',
      location: { field: 'ue-file' },
    });
  }
  let fileBytes: number;
  try {
    fileBytes = statSync(ueFile).size;
  } catch {
    throw new CliValidationError('The UE JSONL file could not be read.', {
      code: 'LOCAL_DATA_UE_FILE_NOT_FOUND',
      location: { field: 'ue-file' },
    });
  }
  if (await sha256File(ueFile) !== manifest.output.valid_sha256) {
    throw new CliValidationError('The UE file fingerprint does not match the manifest.', {
      code: 'LOCAL_DATA_UE_FILE_CHANGED',
      location: { field: 'ue-file' },
    });
  }
  const recordCount = await validateUeFile(ueFile);
  if (recordCount !== manifest.output.valid_records) {
    throw new CliValidationError('The UE record count does not match the manifest.', {
      code: 'LOCAL_DATA_UE_COUNT_MISMATCH',
      location: { field: 'ue-file' },
    });
  }
  if (enforceReady && manifest.status === 'blocked' && !ctx.bool('allow-clean-subset')) {
    throw new CliValidationError('The manifest is blocked because rows were quarantined.', {
      code: 'LOCAL_DATA_CLEAN_SUBSET_CONFIRMATION_REQUIRED',
      hint: 'Review manifest and invalid.rows.jsonl statistics, then explicitly pass --allow-clean-subset if the valid subset may be uploaded.',
      location: { field: 'allow-clean-subset' },
    });
  }
  const resumeFrom = ctx.num('resume-from');
  if (resumeFrom > recordCount) {
    throw new CliValidationError('Resume position exceeds the UE record count.', {
      code: 'LOCAL_DATA_RESUME_OUT_OF_RANGE',
      location: { field: 'resume-from' },
    });
  }
  const batchSize = ctx.num('batch-size');
  return {
    endpoint,
    appid,
    ueFile,
    manifest,
    batchSize,
    resumeFrom,
    recordCount,
    fileBytes,
    batchCount: Math.ceil(Math.max(0, recordCount - resumeFrom) / batchSize),
  };
}

function readManifest(path: string): LocalDataManifest {
  let value: unknown;
  try {
    value = JSON.parse(readFileSync(path, 'utf8'));
  } catch {
    throw new CliValidationError('The local-data manifest could not be read as JSON.', {
      code: 'LOCAL_DATA_MANIFEST_INVALID',
      location: { field: 'manifest' },
    });
  }
  if (!isRecord(value)
    || value.version !== 'ae-local-data-manifest/v1'
    || !isRecord(value.output)
    || typeof value.output.valid_file !== 'string'
    || basename(value.output.valid_file) !== value.output.valid_file
    || typeof value.output.valid_sha256 !== 'string'
    || !/^[a-f0-9]{64}$/i.test(value.output.valid_sha256)
    || !Number.isInteger(value.output.valid_records)
    || value.output.valid_records < 0
    || (value.status !== 'ready' && value.status !== 'blocked')) {
    throw new CliValidationError('The manifest is not ae-local-data-manifest/v1.', {
      code: 'LOCAL_DATA_MANIFEST_INVALID',
      location: { field: 'manifest' },
    });
  }
  return value as unknown as LocalDataManifest;
}

async function validateUeFile(path: string): Promise<number> {
  let count = 0;
  const lines = createInterface({ input: createReadStream(path), crlfDelay: Infinity });
  for await (const line of lines) {
    if (!line.trim()) continue;
    count += 1;
    let value: unknown;
    try {
      value = JSON.parse(line);
    } catch {
      throw invalidUeFile(count);
    }
    if (!isRecord(value) || !isUeRecordType(value['#type'])) {
      throw invalidUeFile(count);
    }
  }
  return count;
}

const UE_RECORD_TYPES = new Set([
  'track',
  'user_set',
  'user_setOnce',
  'user_add',
  'user_unset',
  'user_del',
  'user_append',
  'user_uniq_append',
]);

function isUeRecordType(value: unknown): boolean {
  return typeof value === 'string' && UE_RECORD_TYPES.has(value);
}

function decorateBatchError(
  error: unknown,
  completedRecords: number,
  completedBatches: number,
  batchStart: number,
  batchSize: number,
): unknown {
  if (!(error instanceof LocalDataUploadError)) return error;
  const deliveryUnknown = error.meta?.delivery_state === 'unknown';
  return new LocalDataUploadError(error.message, {
    code: error.code,
    httpStatus: error.httpStatus,
    hint: error.hint,
    meta: {
      ...error.meta,
      completed_records: completedRecords,
      completed_batches: completedBatches,
      ...(deliveryUnknown
        ? {
            uncertain_batch_start: batchStart,
            uncertain_batch_size: batchSize,
            resume_from_after_verification: batchStart,
          }
        : {
            failed_batch_start: batchStart,
            failed_batch_size: batchSize,
          }),
    },
    cause: error,
  });
}

async function* readUeBatches(path: string, offset: number, batchSize: number): AsyncGenerator<string[]> {
  let index = 0;
  let batch: string[] = [];
  const lines = createInterface({ input: createReadStream(path), crlfDelay: Infinity });
  for await (const line of lines) {
    if (!line.trim()) continue;
    if (index++ < offset) continue;
    batch.push(line);
    if (batch.length >= batchSize) {
      yield batch;
      batch = [];
    }
  }
  if (batch.length > 0) yield batch;
}

function invalidUeFile(record: number): CliValidationError {
  return new CliValidationError('The UE JSONL file contains an invalid record.', {
    code: 'LOCAL_DATA_UE_FILE_INVALID',
    location: { record },
  });
}

function endpointError(): CliValidationError {
  return new CliValidationError('A complete http(s) receiver endpoint ending in /sync_json is required.', {
    code: 'LOCAL_DATA_ENDPOINT_INVALID',
    location: { field: 'endpoint' },
  });
}

function maskEndpoint(endpoint: string): string {
  const url = new URL(endpoint);
  const parts = url.hostname.split('.');
  const first = parts[0];
  parts[0] = first.length <= 2 ? '**' : `${first[0]}***${first.at(-1)}`;
  return `${url.protocol}//${parts.join('.')}${url.port ? `:${url.port}` : ''}/sync_json`;
}

function maskAppid(appid: string): string {
  return appid.length <= 4 ? '****' : `${'*'.repeat(Math.min(8, appid.length - 4))}${appid.slice(-4)}`;
}

function isRecord(value: unknown): value is Record<string, any> {
  return value !== null && typeof value === 'object' && !Array.isArray(value);
}
