import { createMcpCommand, optionalBoolean, optionalJson, optionalNumber, optionalString } from '../shared.js';

export const queryBiPanelData = createMcpCommand({
  command: '+query_bi_panel_data',
  description: 'Query released BI panel data. Use result_type=charts for page chart data as columns and rows, or result_type=summary for summary markdown and blocks. Call get_bi_panel_detail first to obtain pageKey, chartIds, columns, and control schemas. For long-running or cancelable queries, provide requestId before starting. For any query that may exceed the CLI or MCP HTTP timeout, preset requestId so you can call +cancel_query --request_id <same value> if you stop waiting or the request returns fetch failed. If fetch failed, HTTP timeout, or caller timeout happens, the backend query may still be running. If provided, requestId must use mcp_<32 lowercase hex UUID>, for example mcp_0123456789abcdef0123456789abcdef. Submitted queries return metadata.requestId; pass that value to cancel_query(requestId) when the query is no longer needed. The auto-generated requestId is not available when the HTTP request fails before a response, so preset requestId is required for proactive cleanup.',
  flags: [
    { name: 'project_id', type: 'number', required: true, desc: 'Project ID', alias: 'p' },
    { name: 'panel_id', type: 'number', required: true, desc: 'BI panel ID returned by +list_bi_panels' },
    { name: 'page_key', type: 'string', required: true, desc: 'Page key returned by +get_bi_panel_detail' },
    { name: 'result_type', type: 'string', required: true, desc: 'Result type. Supported values: charts, summary.' },
    { name: 'request_id', type: 'string', required: false, desc: 'Optional unique request ID used for tracking and cancellation. If provided, it must use mcp_<32 lowercase hex UUID>, for example mcp_0123456789abcdef0123456789abcdef. For long-running or cancelable queries, provide this before starting the query so it can be cancelled later with +cancel_query --request_id <same value>, even if the caller stops waiting before the tool returns. If fetch failed, HTTP timeout, or caller timeout happens, the backend query may still be running. The auto-generated requestId is not available when the HTTP request fails before a response, so preset requestId is required for proactive cleanup. Generated automatically if omitted. The response metadata.requestId can also be passed to cancel_query when the query is no longer needed.' },
    { name: 'chart_ids', type: 'json', required: false, desc: 'Optional chart IDs when result_type=charts. If omitted, all queryable charts on the page are queried.' },
    { name: 'parameter_controls', type: 'json', required: false, desc: 'Optional dashboard-level parameter control overrides. Each item must have controlId and one scalar value.' },
    { name: 'permission_controls', type: 'json', required: false, desc: 'Optional dashboard-level permission control values. Each item must have controlId and value. value may be one scalar or an array; allowedValues are hints, not an MCP-side whitelist.' },
    { name: 'chart_filter_controls', type: 'json', required: false, desc: 'Optional page chart filter control values. Each item must have controlId and value. value may be one scalar or an array and applies only to bound charts.' },
    { name: 'columns', type: 'json', required: false, desc: 'Optional returned columns for chart data. Must match columns returned by +get_bi_panel_detail.' },
    { name: 'row_limit', type: 'number', required: false, desc: 'Optional chart row limit. Default: 50, maximum: 10000.' },
    { name: 'row_offset', type: 'number', required: false, desc: 'Optional chart row offset. Default: 0.' },
    { name: 'block_limit', type: 'number', required: false, desc: 'Optional summary block limit. Default: 20, maximum: 10000.' },
    { name: 'block_offset', type: 'number', required: false, desc: 'Optional summary block offset. Default: 0.' },
    { name: 'use_cache', type: 'boolean', required: false, desc: 'Whether to use cache. Default: true.' },
    { name: 'timeout_minutes', type: 'number', required: false, desc: 'Query timeout in minutes. Default: 3, minimum: 1, maximum: 10.' },
  ],
  risk: 'read',
  buildArgs: (ctx) => ({
    projectId: ctx.num('project_id'),
    panelId: ctx.num('panel_id'),
    pageKey: ctx.str('page_key'),
    resultType: ctx.str('result_type'),
    requestId: optionalString(ctx, 'request_id'),
    chartIds: optionalJson(ctx, 'chart_ids'),
    parameterControls: optionalJson(ctx, 'parameter_controls'),
    permissionControls: optionalJson(ctx, 'permission_controls'),
    chartFilterControls: optionalJson(ctx, 'chart_filter_controls'),
    columns: optionalJson(ctx, 'columns'),
    rowLimit: optionalNumber(ctx, 'row_limit'),
    rowOffset: optionalNumber(ctx, 'row_offset'),
    blockLimit: optionalNumber(ctx, 'block_limit'),
    blockOffset: optionalNumber(ctx, 'block_offset'),
    useCache: optionalBoolean(ctx, 'use_cache'),
    timeoutMinutes: optionalNumber(ctx, 'timeout_minutes'),
  }),
});
