import {
  compactInput,
  createAnalysisCapabilityCommand,
  optionalJson,
  optionalJsonArray,
  optionalNumber,
  optionalString,
  payloadFlag,
  projectIdFlag,
  projectInput,
} from '../capability-shared.js';

export const dashboardUpdate = createAnalysisCapabilityCommand({
  resource: 'dashboard',
  command: 'update',
  capabilityId: 'analysis.dashboard.update',
  description: 'Update dashboard settings, create/update a dashboard note, or replace the dashboard-level business filter. Use --operation settings, note-upsert, or business-filter.',
  flags: [
    projectIdFlag,
    { name: 'operation', type: 'string', required: true, desc: 'Update operation: settings, note-upsert, or business-filter.' },
    { name: 'dashboard-id', type: 'number', required: false, desc: 'Dashboard ID for a single-dashboard update.' },
    { name: 'dashboard-ids', type: 'json', required: false, desc: 'Dashboard ID array for batch settings updates.' },
    { name: 'dashboard-name', type: 'string', required: false, desc: 'Dashboard name for single rename.' },
    { name: 'zone-offset', type: 'number', required: false, desc: 'Fixed dashboard time zone offset in hours. For example, UTC+8 is 8 and UTC-5 is -5. Valid range: -12 to 14.' },
    { name: 'refresh-type', type: 'number', required: false, desc: 'Dashboard refresh type: 0 real-time, 1 scheduled.', min: 0, max: 1 },
    { name: 'dashboard-status', type: 'string', required: false, desc: 'Dashboard status: normal or freeze.' },
    { name: 'note-id', type: 'number', required: false, desc: 'Dashboard note ID. Omit to create a new note.' },
    { name: 'note-title', type: 'string', required: false, desc: 'Dashboard note title.' },
    { name: 'description', type: 'string', required: false, desc: 'Dashboard note description.' },
    { name: 'ui-config', type: 'string', required: false, desc: 'Dashboard or note UI config string.' },
    { name: 'filter', type: 'json', required: false, desc: 'Dashboard-level business filter in snake_case QP form. Required with --operation business-filter. Pass {"junction_kind":"and","ta_filters":[]} to clear it.' },
    payloadFlag,
  ],
  risk: 'write',
  buildInput: (ctx) => compactInput({
    ...projectInput(ctx),
    operation: ctx.str('operation'),
    dashboard_id: optionalNumber(ctx, 'dashboard-id'),
    dashboard_ids: optionalJsonArray(ctx, 'dashboard-ids'),
    dashboard_name: optionalString(ctx, 'dashboard-name'),
    zone_offset: optionalNumber(ctx, 'zone-offset'),
    refresh_type: optionalNumber(ctx, 'refresh-type'),
    dashboard_status: optionalString(ctx, 'dashboard-status'),
    note_id: optionalNumber(ctx, 'note-id'),
    note_title: optionalString(ctx, 'note-title'),
    description: optionalString(ctx, 'description'),
    ui_config: optionalString(ctx, 'ui-config'),
    filter: optionalJson(ctx, 'filter'),
    payload: optionalJson(ctx, 'payload'),
  }),
});
