import {
  compactInput,
  createAnalysisMetaCapabilityCommand,
  fieldsFlag,
  limitFlag,
  offsetFlag,
  optionalBoolean,
  optionalJson,
  optionalNumber,
  optionalString,
  projectIdFlag,
  projectInput,
  queryFlag,
} from '../../capability-shared.js';

export const metadataPropertyList = createAnalysisMetaCapabilityCommand({
  resource: 'property',
  command: 'list',
  capabilityId: 'metadata.property.list',
  description: 'List event or user properties with optional search, field projection, pagination, and authentication filtering.',
  flags: [
    projectIdFlag,
    { name: 'table-type', type: 'string', required: false, desc: 'Optional property table type: event or user.' },
    { name: 'scope', type: 'string', required: false, desc: 'Optional property scope: event or user.' },
    { name: 'event-name', type: 'string', required: false, desc: 'Optional event name filter for event properties.' },
    queryFlag,
    fieldsFlag,
    limitFlag,
    offsetFlag,
    { name: 'authenticated-only', type: 'boolean', required: false, desc: 'When true, return only authenticated properties.' },
  ],
  risk: 'read',
  buildInput: (ctx) => compactInput({
    ...projectInput(ctx),
    table_type: optionalString(ctx, 'table-type'),
    scope: optionalString(ctx, 'scope'),
    event_name: optionalString(ctx, 'event-name'),
    query: optionalString(ctx, 'query'),
    fields: optionalJson(ctx, 'fields'),
    limit: optionalNumber(ctx, 'limit'),
    offset: optionalNumber(ctx, 'offset'),
    authenticated_only: optionalBoolean(ctx, 'authenticated-only'),
  }),
});
